site_name: Secure Device Onboard
theme:
  name: 'material'
  logo: 'images/securedeviceonboard-icon-color.png'
  extra:
  search:
    language: 'en'
  favicon: 'images/securedeviceonboard-icon-color.png'